; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = xbox_control

[env:xbox_control]
build_src_filter = +<xboxControlConnect.cpp>
platform = espressif32
board = esp32s3box
framework = arduino
monitor_speed = 115200
lib_extra_dirs = ~/Documents/Arduino/libraries
board_build.partitions = huge_app.csv
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.f_flash = 80000000L
lib_deps = 
	asukiaaa/XboxSeriesXControllerESP32_asukiaaa @ ^1.1.1
	h2zero/NimBLE-Arduino @ ^2.5.0
	madhephaestus/ESP32Servo@^3.2.1
monitor_filters = esp32_exception_decoder

[env:xbox_control_turn]
build_src_filter = +<xboxControlConnect_turn.cpp>
platform = espressif32
board = esp32s3box
framework = arduino
monitor_speed = 115200
lib_extra_dirs = ~/Documents/Arduino/libraries
board_build.partitions = huge_app.csv
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.f_flash = 80000000L
lib_deps = 
	asukiaaa/XboxSeriesXControllerESP32_asukiaaa @ ^1.1.1
	h2zero/NimBLE-Arduino @ ^2.5.0
	madhephaestus/ESP32Servo@^3.2.1
monitor_filters = esp32_exception_decoder

[env:servo_control]
build_src_filter = +<servoControl.cpp>
platform = espressif32
board = esp32s3box
framework = arduino
monitor_speed = 115200
lib_extra_dirs = ~/Documents/Arduino/libraries
board_build.partitions = huge_app.csv
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.f_flash = 80000000L
lib_deps = 
	asukiaaa/XboxSeriesXControllerESP32_asukiaaa @ ^1.1.1
	h2zero/NimBLE-Arduino @ ^2.5.0
	madhephaestus/ESP32Servo@^3.2.1
monitor_filters = esp32_exception_decoder

[env:full_control]
build_src_filter = +<servoWithRCControl.cpp>
platform = espressif32
board = esp32s3box
framework = arduino
monitor_speed = 115200
lib_extra_dirs = ~/Documents/Arduino/libraries
board_build.partitions = huge_app.csv
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.f_flash = 80000000L
lib_deps = 
	asukiaaa/XboxSeriesXControllerESP32_asukiaaa @ ^1.1.1
	h2zero/NimBLE-Arduino @ ^2.5.0
	madhephaestus/ESP32Servo@^3.2.1
monitor_filters = esp32_exception_decoder